// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addressbook.proto

/*
Package addressbook is a generated protocol buffer package.

It is generated from these files:
	addressbook.proto

It has these top-level messages:
	Person
	AddressBook
*/
package addressbook

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 枚举类型的第一个字段必须为0
type Person_PhoneType int32

const (
	Person_MOBILE Person_PhoneType = 0
	Person_HOME   Person_PhoneType = 1
	Person_WORK   Person_PhoneType = 2
)

var Person_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}
var Person_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Person_PhoneType) String() string {
	return proto.EnumName(Person_PhoneType_name, int32(x))
}
func (Person_PhoneType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Person struct {
	Name   string          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Id     int32           `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Phones []*Person_Phone `protobuf:"bytes,3,rep,name=phones" json:"phones,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Person) GetPhones() []*Person_Phone {
	if m != nil {
		return m.Phones
	}
	return nil
}

type Person_Phone struct {
	Number string           `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Type   Person_PhoneType `protobuf:"varint,2,opt,name=type,enum=addressbook.Person_PhoneType" json:"type,omitempty"`
}

func (m *Person_Phone) Reset()                    { *m = Person_Phone{} }
func (m *Person_Phone) String() string            { return proto.CompactTextString(m) }
func (*Person_Phone) ProtoMessage()               {}
func (*Person_Phone) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Person_Phone) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Person_Phone) GetType() Person_PhoneType {
	if m != nil {
		return m.Type
	}
	return Person_MOBILE
}

type AddressBook struct {
	Persons []*Person `protobuf:"bytes,1,rep,name=persons" json:"persons,omitempty"`
}

func (m *AddressBook) Reset()                    { *m = AddressBook{} }
func (m *AddressBook) String() string            { return proto.CompactTextString(m) }
func (*AddressBook) ProtoMessage()               {}
func (*AddressBook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddressBook) GetPersons() []*Person {
	if m != nil {
		return m.Persons
	}
	return nil
}

func init() {
	proto.RegisterType((*Person)(nil), "addressbook.Person")
	proto.RegisterType((*Person_Phone)(nil), "addressbook.Person.Phone")
	proto.RegisterType((*AddressBook)(nil), "addressbook.AddressBook")
	proto.RegisterEnum("addressbook.Person_PhoneType", Person_PhoneType_name, Person_PhoneType_value)
}

func init() { proto.RegisterFile("addressbook.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4c, 0x49, 0x29,
	0x4a, 0x2d, 0x2e, 0x4e, 0xca, 0xcf, 0xcf, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0x7a, 0xc0, 0xc8, 0xc5, 0x16, 0x90, 0x5a, 0x54, 0x9c, 0x9f, 0x27, 0x24, 0xc4, 0xc5,
	0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b, 0xf1, 0x71,
	0x31, 0x65, 0xa6, 0x48, 0x30, 0x29, 0x30, 0x6a, 0xb0, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x19, 0x72,
	0xb1, 0x15, 0x64, 0xe4, 0xe7, 0xa5, 0x16, 0x4b, 0x30, 0x2b, 0x30, 0x6b, 0x70, 0x1b, 0x49, 0xea,
	0x21, 0x9b, 0x0f, 0x31, 0x48, 0x2f, 0x00, 0xa4, 0x22, 0x08, 0xaa, 0x50, 0x2a, 0x88, 0x8b, 0x15,
	0x2c, 0x20, 0x24, 0xc6, 0xc5, 0x96, 0x57, 0x9a, 0x9b, 0x94, 0x5a, 0x04, 0xb5, 0x01, 0xca, 0x13,
	0x32, 0xe4, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x05, 0xdb, 0xc2, 0x67, 0x24, 0x8b, 0xd3, 0xc4, 0x90,
	0xca, 0x82, 0xd4, 0x20, 0xb0, 0x52, 0x25, 0x6d, 0x2e, 0x4e, 0xb8, 0x90, 0x10, 0x17, 0x17, 0x9b,
	0xaf, 0xbf, 0x93, 0xa7, 0x8f, 0xab, 0x00, 0x83, 0x10, 0x07, 0x17, 0x8b, 0x87, 0xbf, 0xaf, 0xab,
	0x00, 0x23, 0x88, 0x15, 0xee, 0x1f, 0xe4, 0x2d, 0xc0, 0xa4, 0x64, 0xc3, 0xc5, 0xed, 0x08, 0x31,
	0xd2, 0x29, 0x3f, 0x3f, 0x5b, 0x48, 0x97, 0x8b, 0xbd, 0x00, 0x6c, 0x6a, 0xb1, 0x04, 0x23, 0xd8,
	0x0f, 0xc2, 0x58, 0x6c, 0x0c, 0x82, 0xa9, 0x49, 0x62, 0x03, 0x07, 0x9a, 0x31, 0x20, 0x00, 0x00,
	0xff, 0xff, 0xf2, 0x7a, 0x7a, 0xe0, 0x49, 0x01, 0x00, 0x00,
}
